# Generated by Django 5.2 on 2025-05-06 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgriculturalData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                ("crop", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("area_harvested_ha", models.FloatField()),
                ("production_tonnes", models.FloatField()),
                ("rainfall_mm", models.FloatField()),
                ("temperature_c", models.FloatField()),
                ("price_usd_per_tonne", models.FloatField()),
                ("policy_flag", models.CharField(max_length=50)),
                ("transport_cost_usd", models.FloatField()),
                ("demand_supply_gap", models.FloatField()),
                ("productivity_index", models.FloatField(default=0)),
                ("predicted_production", models.FloatField(blank=True, null=True)),
                ("predicted_yield", models.FloatField(blank=True, null=True)),
                ("predicted_price", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Agricultural Data",
                "ordering": ["-year", "country"],
            },
        ),
    ]
